require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.0

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']