version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:

  rspec-test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    resource_class: small
    environment:
      COVERAGE: true
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run rspec << parameters.ruby-version >>
          command: bundle exec rspec
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash)
  
  rubocop:
    docker:
      - image: cimg/ruby:2.5
    resource_class: small
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  release:
    parameters:
      tag:
        type: string
        default: "default-tag"
    docker:
      - image: cimg/ruby:2.6.6
    resource_class: small
    environment:
      RELEASE_TAG: << parameters.tag >>
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up credentials
          command: |
              mkdir -p $HOME/.gem
              touch $HOME/.gem/credentials
              chmod 0600 $HOME/.gem/credentials
              printf -- "---\n:rubygems_api_key: $RUBYGEMS_API_KEY\n" > $HOME/.gem/credentials
      - run: 
          name: Set version
          command: sed -i "s/[[:digit:]].[[:digit:]].[[:digit:]]/${RELEASE_TAG}/g" $(find . -name "version.rb")   
      - run:
          name: Build gem
          command: gem build *.gemspec
      - run:
          name: Push gem
          command: gem push *.gem

workflows:
  
  settings_reader.build:
    jobs:

      - rspec-test:
          name: RSpec Test
          matrix:
            parameters:
              ruby-version: [ '2.5', '2.6', '2.7', '3.0' ]

      - rubocop:
          name: Rubocop
      
  settings_reader.release:
    jobs:

      - release:
          tag: << pipeline.git.tag >>
          context: gem-publishing
          filters:
            branches:
              ignore: /.*/
            tags: 
              only: /\d\.\d\.\d/
